networks:
    yape_microservices_network:
        driver: bridge

services:
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: yape_sqlserver
        ports:
            - "14330:1433"
        environment:
            SA_PASSWORD: "MyWeakPassword:)"
            ACCEPT_EULA: "Y"
        networks:
            - yape_microservices_network

    zookeeper:
        image: confluentinc/cp-zookeeper:7.3.0
        container_name: yape_zookeeper
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        networks:
            - yape_microservices_network

    kafka:
        image: confluentinc/cp-kafka:7.3.0
        hostname: yape_kafka
        container_name: yape_kafka
        depends_on:
            zookeeper:
                condition: service_started
        ports:
            - "9092:9092"
        environment:
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        networks:
            - yape_microservices_network

    antifraud_service:
        build:
            context: .
            dockerfile: ./AntiFraudService/Dockerfile
        container_name: antifraud_service
        depends_on:
            kafka:
                condition: service_started
        environment:
            KAFKA_BROKER: "kafka:9092"
        ports:
            - "9080:8080"
            - "9081:8081"
        networks:
            - yape_microservices_network

    transaction_service:
        build:
            context: .
            dockerfile: ./TransactionService/Dockerfile
        container_name: transaction_service
        depends_on:
            - kafka
            - sqlserver
        environment:
            KAFKA_BROKER: "kafka:9092"
        ports:
            - "8080:8080"
            - "8081:8081"
        networks:
            - yape_microservices_network